export enum TaskPriority {
    SET_PROJECTS = 'SET_PROJECTS',
    GET_PROJECTS = 'GET_PROJECTS',
    CREATE_PROJECT = 'CREATE_PROJECT',
    EDIT_PROJECT = 'EDIT_PROJECT',
    SAVE_PROJECT = 'SAVE_PROJECT',
    CANCEL_EDIT = 'CANCEL_EDIT'
}